### ISSUE TITLE
log函数在传入参数时，参数数值异常

### ISSUE THREAD

**Issue by HuajiSeries** [ylongwang2782/GD32_Clang_CMake_template#3]
Log.d("%d",num);
此时num数值异常

**Comment by ylongwang2782** [comment]
![image](https://github.com/user-attachments/assets/0efcd3a1-5f49-4211-9de0-1ff26629c606)
具体情况如上图所示
以下是打印代码
```c
void ledBlinkTask(void *pvParameters) {
    int count = 0;
    for (;;) {
        Log.d("Led Blink counts: %d", count);
        led0.toggle();
        vTaskDelay(500);
    }
}
```

**Comment by HuajiSeries** [comment]
Logger::d 未传递可变参数 ...，导致 Logger::log 中的 va_list args 初始化失败。
拓展d函数，d函数中创建list并直接赋给log；调整log，使其接收并处理d所创建的list，而不再自行创建一个。
[b70c49e](https://github.com/ylongwang2782/GD32_Clang_CMake_template/commit/b70c49edb8b2196eb82dbb4eefffc549c85625ec)
